[package]
name = "sp1-prover-master"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
sp1-sdk = { version = "1.0.1", features = ["network", "native-gnark"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
reqwest = "0.12.5"
tokio = { version = "1.39.2", features = ["full"] }
anyhow = "1.0.86"
log = "0.4.22"
